<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="475042" started-at="2018-10-08T08:25:16Z" finished-at="2018-10-08T08:33:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="475042" started-at="2018-10-08T08:25:16Z" finished-at="2018-10-08T08:33:11Z">
      <class name="net.wangxinli.testng.TestngCase1">
        <test-method status="PASS" signature="init()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="init" is-config="true" duration-ms="77175" started-at="2018-10-08T16:25:16Z" finished-at="2018-10-08T16:26:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="login()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="login" is-config="true" duration-ms="31744" started-at="2018-10-08T16:26:33Z" finished-at="2018-10-08T16:27:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="test001_editStore()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="test001_editStore" duration-ms="230443" started-at="2018-10-08T16:27:05Z" finished-at="2018-10-08T16:30:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[编辑门店失败]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 编辑门店失败
	at org.testng.Assert.fail(Assert.java:94)
	at net.wangxinli.testng.TestngCase1.test001_editStore(TestngCase1.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001_editStore -->
        <test-method status="PASS" signature="restart()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="restart" is-config="true" duration-ms="14568" started-at="2018-10-08T16:30:56Z" finished-at="2018-10-08T16:31:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restart -->
        <test-method status="PASS" signature="login()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="login" is-config="true" duration-ms="30442" started-at="2018-10-08T16:31:10Z" finished-at="2018-10-08T16:31:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="test002_prepare()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="test002_prepare" duration-ms="77556" started-at="2018-10-08T16:31:41Z" finished-at="2018-10-08T16:32:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002_prepare -->
        <test-method status="PASS" signature="restart()[pri:0, instance:net.wangxinli.testng.TestngCase1@66d2e7d9]" name="restart" is-config="true" duration-ms="12923" started-at="2018-10-08T16:32:58Z" finished-at="2018-10-08T16:33:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- restart -->
      </class> <!-- net.wangxinli.testng.TestngCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
